# Generated by Django 3.1.2 on 2021-01-30 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.department'),
        ),
    ]
