# Generated by Django 3.1.2 on 2021-01-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210129_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='department',
        ),
    ]
