# Generated by Django 3.1.2 on 2021-01-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_question_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
