# Generated by Django 3.1.2 on 2021-02-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210130_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceUsernames',
        ),
    ]
